//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Support
    {
        public int VNo { get; set; }
        public int SNo { get; set; }
        public string Name { get; set; }
    
        public virtual Voucher Voucher { get; set; }
    }
}
